apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sourcedeck-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "30m"
spec:
  ingressClassName: nginx
  tls:
    - hosts: ["api.sourcedeck.app"]
      secretName: sourcedeck-tls
  rules:
    - host: api.sourcedeck.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sourcedeck-api
                port: { number: 80 }
